config/routes.rb
Rails.application.routes.draw do
  resources :departments  
  resources :members
  resources :results do
    collection {post :import }
  end

  resources :videos
  resources :tutorials
  resources :notifications
  resources :magazines
  
  resources :articles do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end

  resources :comments do
    resources :comments
  end

  resources :documents do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end
  
  get 'home/index'
  get 'home/search'
  devise_for :users, :skip => [:registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  #put 'approve_document', to: 'documents#approve_document', as: 'approve_document'
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
    belongs_to :user
    before_save :upcase_fields
    has_many :comments, as: :commentable

    APPROVED = 'Approved'
    IN_REVIEW = 'In Review'
    REJECTED = 'Rejected'

    validates :title, presence: true
    validates :keywords, presence: true
    validates :content, presence: true
    validates :user_id, presence: true

    belongs_to :reviewer1, class_name: 'User', foreign_key: 'reviewer1_id', optional: true
    belongs_to :reviewer2, class_name: 'User', foreign_key: 'reviewer2_id', optional: true
    belongs_to :reviewer3, class_name: 'User', foreign_key: 'reviewer3_id', optional: true

    def upcase_fields
        self.title.upcase!
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[ show edit update destroy approve reject]
  before_action :authrize_access


  # GET /articles or /articles.json
  def index
    @articles = current_user.articles.all.order("id DESC")
    if !current_user.is_student?
      @review_arts = Article.where("approval_status = :in_review AND (reviewer1_id IS NULL OR reviewer1_id != :user_id ) AND (reviewer2_id IS NULL OR reviewer2_id != :user_id) AND (reviewer3_id IS NULL OR reviewer3_id != :user_id)", {in_review: Article::IN_REVIEW, user_id: current_user.id}).order("id DESC")
      @approved_articles = Article.where("reviewer1_id = :user_id OR reviewer2_id = :user_id OR reviewer3_id = :user_id", {user_id: current_user.id}).order("id DESC")
    else
      @review_arts = []    
      @approved_articles = []
    end
  end

  # GET /articles/1 or /articles/1.json
  def show 

    if @article.reference_url.present?
      begin
        url = URI("https://api.qrcode-monkey.com/qr/custom")
        https = Net::HTTP.new(url.host, url.port)
        https.use_ssl = true
        request = Net::HTTP::Post.new(url)
        request["Content-Type"] = "text/plain"
        request.body = {"data":"#{@article.reference_url}","config":{"body":"circle-zebra-vertical","eye":"frame13","eyeBall":"ball15","erf1":[],"erf2":[],"erf3":[],"brf1":[],"brf2":[],"brf3":[],"bodyColor":"#0277BD","bgColor":"#FFFFFF","eye1Color":"#075685","eye2Color":"#075685","eye3Color":"#075685","eyeBall1Color":"#0277BD","eyeBall2Color":"#0277BD","eyeBall3Color":"#0277BD","gradientColor1":"#075685","gradientColor2":"#0277BD","gradientType":"linear","gradientOnEyes":false,"logo":"https://raw.githubusercontent.com/shaik1729/sea/development/app/assets/images/sea_logo.jpeg","logoMode":"default"},"size":300,"download":false,"file":"png"}.to_json
        response = https.request(request)
        @qrcode = Base64.strict_encode64(response.read_body)
      rescue => exception
        puts "*************************************#{exception}**************************"
        @qrcode = nil
      end
    else
      @qrcode = nil
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    if !current_user.is_student?
      @article.approval_status = Article::APPROVED
    else
      @article.approval_status = Article::IN_REVIEW
    end

    @article.reviewer1_id = nil
    @article.reviewer2_id = nil
    @article.reviewer3_id = nil
  
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def approve
    if @article.reviewer1_id == nil
      @article.reviewer1_id = current_user.id
    elsif @article.reviewer2_id == nil
      @article.reviewer2_id = current_user.id
    elsif @article.reviewer3_id == nil
      @article.reviewer3_id = current_user.id
      @article.approval_status = Article::APPROVED
      ArticleApprovalMailer.with(user: current_user, status: Article::APPROVED, article: @article).approval_status.deliver_later
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path, notice: "Article Approved." }
        format.json { render :show, status: :approved, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end 
    end
  end

  def reject
    if @article.reviewer1_id == nil
      @article.reviewer1_id = current_user.id
    elsif @article.reviewer2_id == nil
      @article.reviewer2_id = current_user.id
    elsif @article.reviewer3_id == nil
      @article.reviewer3_id = current_user.id
    end
    @article.approval_status = Article::REJECTED

    respond_to do |format|
      if @article.save
        ArticleApprovalMailer.with(user: current_user, status: Article::REJECTED, article: @article, message: params[:reason]).approval_status.deliver_later
        format.html { redirect_to articles_path, notice: "Article Rejected." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end 
    end
  end

  def search
    if params[:id].empty?
      @articles = Article.where("approval_status = ? and title like ?", Article::APPROVED, "%#{params[:title]}%".upcase!).order("id DESC")
    else
      @articles = Article.where("approval_status = ? and id = ?", Article::APPROVED, params[:id][1..]).order("id DESC")
    end

    if @articles.empty?
      redirect_to articles_path, notice: "Article Not Found."
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def authrize_access
      if current_user.is_student?
        raise 'Unauthorized' unless (['index', 'new', 'create', 'show', 'search'].include?(params[:action]))
        if @article.present?
          raise 'Unauthorized' if ((@article.user != current_user) && (@article.approval_status != Article::APPROVED))
        end 
      else
        if ['edit', 'update', 'destroy'].include?(params[:action])
          raise 'Unauthorized' unless @article.user == current_user
        elsif ['approve', 'reject'].include?(params[:action])
          raise 'Unauthorized' unless @article.user.is_student?
          if params[:action] == 'approve'
            raise 'Unauthorized' if (@article.approval_status == Article::APPROVED)
          elsif params[:action] == 'reject'
            raise 'Unauthorized' if (@article.approval_status == Article::REJECTED)
          end
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :keywords, :approval_status, :reviewer1_id, :reviewer2_id, :reviewer3_id, :content, :user_id, :reference_url)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def show_article_approve_button?
       (current_user.role.code != "STU") && (@article.approval_status == Article::IN_REVIEW) && !([@article.reviewer1, @article.reviewer2, @article.reviewer3].include? current_user)
    end

    def show_article_comments?
        @article.approval_status == Document::APPROVED
    end

    def show_article_approval_status?
        @article.user == current_user && current_user.is_student?
    end
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <div class="alert alert-danger" role="alert">
            <%= error.full_message %>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-2">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :keywords, class: "form-label" %>
    <%= form.text_field :keywords, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :content, class: "form-label" %>
    <%= form.rich_text_area :content, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :reference_url, class: "form-label" %>
    <%= form.text_field :reference_url, class: "form-control" %>
  </div>

  <div class="field d-none">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions mt-2">
    <%= form.submit class: "btn btn-success mt-4" %>
  </div>
<% end %>

app/views/articles/_search_form.html.erb
<div class="card">
  <h2 class="card-header">
    Article Search
  </h2>
  <div class="card-body">
    <%= form_with url: search_articles_path, local: true, method: :get do  |f| %>
        <%= text_field_tag :id, params[:id], :placeholder => "Enter Article ID", class: "form-control me-2" %>
        <p>OR</p>
        <%= text_field_tag :title, params[:title], :placeholder => "Enter Article Title", class: "form-control me-2" %>
        <div class="actions mt-2">
            <%= f.submit "Search", class: "btn btn-success" %>
        </div>
    <% end %>    
  </div>
</div>

app/views/articles/edit.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    Editing Article
  </h2>
  <div class="card-body">
    <%= render 'form', article: @article %>
    <%= link_to '< Back', articles_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/articles/index.html.erb
<%= render 'search_form' %>

<%= link_to 'Create New Article', new_article_path, class: "btn btn-primary mt-4 mb-4" %>

<button class="collapsible">Your Articles</button>
<div class="content">

<div class="table-responsive" >

    <table class="table table-bordered table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Keywords</th>
          <th scope="col" colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td>A<%= article.id %></td>
            <td><%= article.title %></td>
            <td><%= article.keywords %></td>
            <td><%= link_to 'VIEW', article, class: "btn btn-info btn-sm w-100" %></td>
            <% if current_user.is_student? %>
              <td><%= article.approval_status %></td>
            <% else %>
              <td><%= link_to 'Edit', edit_article_path(article), class: "btn btn-primary btn-sm w-100" %></td>
              <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm w-100" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

  
<% if !current_user.is_student? %>
<button class="collapsible">Awaiting Review Articles</button>
<div class="content">
  <div class="table-responsive">
    <table class="table table-bordered table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Keywords</th>
          <th scope="col">Uploaded By</th>
          <th scope="col">Approval status</th>
          <th scope="col">Reviewer1</th>
          <th scope="col">Reviewer2</th>
          <th scope="col">Reviewer3</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @review_arts.each do |article| %>
          <tr>
            <td>A<%= article.id %></td>
            <td><%= article.title %></td>
            <td><%= article.keywords %></td>
            <td><%= article.user.name %></td>
            <td><%= article.approval_status %></td>
            <td><%= article.reviewer1&.name %></td>
            <td><%= article.reviewer2&.name  %></td>
            <td><%= article.reviewer3&.name %></td>
            <td><%= link_to 'VIEW', article, class: "btn btn-info btn-sm w-100" %></td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>
<button class="collapsible">Reviewed Articles</button>
  <div class="content">
    <div class="table-responsive">
      <table class="table table-bordered table-sm">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Keywords</th>
            <th scope="col">Uploaded By</th>
            <th scope="col">Approval status</th>
            <th scope="col">Reviewer1</th>
            <th scope="col">Reviewer2</th>
            <th scope="col">Reviewer3</th>
            <th scope="col" colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @approved_articles.each do |article| %>
            <tr>
              <td>A<%= article.id %></td>
              <td><%= article.title %></td>
              <td><%= article.keywords %></td>
              <td><%= article.user.name %></td>
              <td><%= article.approval_status %></td>
              <td><%= article.reviewer1&.name %></td>
              <td><%= article.reviewer2&.name  %></td>
              <td><%= article.reviewer3&.name %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    New Article
  </h2>
  <div class="card-body">
    <%= render 'form', article: @article %>
    <%= link_to '< Back', articles_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/articles/search.html.erb
<%= render 'search_form' %>

<div class="card mt-4">
  <h2 class="card-header">
    Search Results
  </h2>
  <div class="card-body">
    <div class="table-responsive">

      <table class="table table-bordered table-sm">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Keywords</th>
            <th scope="col">Author</th>
            <th scope="col" colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td>A<%= article.id %></td>
              <td><%= article.title %></td>
              <td><%= article.keywords %></td>
              <td><%= "#{article.user.name} (#{article.user.role.name} #{article.user.department.code})" %></td>
              <td><%= link_to 'VIEW', article, class: "btn btn-info btn-sm w-100" %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <p>
          <strong>Title:</strong>
          <%= @article.title %>
        </p>
  
        <p>
          <strong>Keywords:</strong>
          <%= @article.keywords %>
        </p>
  
        <p>
          <strong>Author:</strong>
          <%= "#{@article.user.name} (#{@article.user.role.name}, #{@article.user.department.name})" %>
        </p>
    
      </div>
      <% if @qrcode %>
        <div class="col">
          <p>
            <strong>Attachments/References:</strong>
            <br>
            <a href="<%= @article.reference_url %>" class="btn btn-primary" target="_blank">Click Here!</a>
          </p>
          <img src="data:image/jpeg;base64,<%= @qrcode %>">
        </div>
      <% end %>
    </div>
      

    <p>
      <%= @article.content %>
    </p>

    <% if show_article_approval_status? %>
      <p>
        <strong>Approval status:</strong>
        <%= @article.approval_status %>
      </p>

      <p>
        <strong>Reviewer1:</strong>
        <%= @article.reviewer1&.name %>
      </p>

      <p>
        <strong>Reviewer2:</strong>
        <%= @article.reviewer2&.name %>
      </p>

      <p>
        <strong>Reviewer3:</strong>
        <%= @article.reviewer3&.name %>
      </p>
    <% end %>


    <% if show_article_approve_button? %>
      <%= form_with url: approve_article_path, local: true, method: :put do  |f| %>
        <div class="actions mt-4 mb-4">
          <%= f.submit "Approve", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= form_with url: reject_article_path, local: true, method: :put do  |f| %>
        <%= text_field_tag :reason, params[:reason], :placeholder => "Enter Reason", class: "form-control me-2",:required => 'required' %>
        <div class="actions mt-4">
          <%= f.submit "Reject", class: "btn btn-danger" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <p>Commenting as</p>
    <div class="row mb-2">
      <div class="col comment_avatar_view">
        <iframe src="https://drive.google.com/file/d/<%= current_user.avatar_url %>/preview" class="avatar"></iframe>
        <p class="m-2"><%= current_user.name.upcase %></p>
      </div>
    </div>
    <%= form_for [@article, Comment.new], method: :post do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_area :content, placeholder: "Add a comment...", class: "form-control" %><br/>
        <%= f.submit "Comment", class: "btn btn-primary mb-4"  %>
    <% end %>

    <% if show_article_comments? %>
      <%= render partial: 'comments/comment', collection: @article.comments.order(id: :desc) %>
    <% end %>

  </div>
</div>