config/routes.rb
Rails.application.routes.draw do
  resources :departments  
  resources :members
  resources :results do
    collection {post :import }
  end

  resources :videos
  resources :tutorials
  resources :notifications
  resources :magazines
  
  resources :articles do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end

  resources :comments do
    resources :comments
  end

  resources :documents do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end
  
  get 'home/index'
  get 'home/search'
  devise_for :users, :skip => [:registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  #put 'approve_document', to: 'documents#approve_document', as: 'approve_document'
end

app/models/notification.rb
class Notification < ApplicationRecord
    has_rich_text :content
    belongs_to :user, optional: true
    belongs_to :regulation, optional: true
    belongs_to :batch, optional: true
    belongs_to :department, optional: true
    belongs_to :course, optional: true

    validates :title, presence: true
    validates :content, presence: true

    before_save :upcase_fields

    def upcase_fields
        self.title.upcase!
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notification, only: %i[ show edit update destroy ]
  before_action :authrize_access

  # GET /notifications or /notifications.json
  def index
    @notifications = Notification.all.order("id DESC")
    if !current_user.is_student?
      @your_notifications = current_user.notifications.all.order("id DESC")
    end
  end

  # GET /notifications/1 or /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications or /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        @from = "#{current_user.name} (#{current_user.role.name} - #{current_user.department.name})"

        NotificationMailer.with(title: @notification.title, regulation_id: @notification.regulation&.id, user_id: @notification.user&.id, batch_id: @notification.batch&.id, department_id: @notification.department&.id, course_id: @notification.course&.id, from: @from, url: notification_url(@notification)).new_notification.deliver_later

        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully created." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1 or /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully updated." }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url, notice: "Notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    def authrize_access
      if current_user.is_student?
        raise 'Unauthorized' unless ['index', 'show'].include?(params[:action])
      else
        if ['edit', 'update', 'destroy'].include?(params[:action])
          raise 'Unauthorized' unless @notification.user == current_user
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:title, :content, :user_id, :regulation_id, :batch_id, :department_id, :course_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.each do |error| %>
          <div class="alert alert-danger" role="alert">
            <%= error.full_message %>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-2">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control"  %>
  </div>

  <div class="field mt-2">
    <%= form.label :content, class: "form-label" %>
    <%= form.rich_text_area :content, class: "form-control"  %>
  </div>

  <div class="field d-none">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, :value => current_user.id %>
  </div>
  
  <div class="field mt-2">
    <%= form.label :regulation_id, class: "form-label" %>
    <%= form.collection_select :regulation_id, Regulation.all, :id, :name, {}, {class: "form-select"}  %>
  </div>

  <div class="field mt-2">
    <%= form.label :batch_id, class: "form-label" %>
    <%= form.collection_select :batch_id, Batch.all, :id, :name, {}, {class: "form-select"}  %>
  </div>

  <div class="field mt-2">
    <%= form.label :department_id, class: "form-label" %>
    <%= form.collection_select :department_id, Department.all, :id, :name, {}, {class: "form-select"}  %>
  </div>

  <div class="field mt-2">
    <%= form.label :course_id, class: "form-label" %>
    <%= form.collection_select :course_id, Course.all, :id, :name, {}, {class: "form-select"}  %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success mt-4" %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    Editing Notification
  </h2>
  <div class="card-body">
    <%= render 'form', notification: @notification %>
    <%= link_to '< Back', notifications_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/notifications/index.html.erb
<% if !current_user.is_student? %>

  <%= link_to 'New Notification', new_notification_path, class: "btn btn-primary mt-4 mb-4" %>

    <button class="collapsible">Your Notifications</button>
    <div class="content">
      <div class="table-responsive">

        <table class="table table-bordered table-sm">
          <thead>
            <tr>
              <th scope="col">Published Date</th>
              <th scope="col">Regulation</th>
              <th scope="col">Batch</th>
              <th scope="col">Department</th>
              <th scope="col">Course</th>
              <th scope="col" colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @your_notifications.each do |notification| %>
              <tr>
                <td><%= notification.created_at.strftime("%d/%m/%Y") %></td>
                <td><%= notification.title %></td>
                <td><%= notification.regulation&.code %></td>
                <td><%= notification.batch&.name %></td>
                <td><%= notification.department&.code %></td>
                <td><%= notification.course&.code %></td>
                <td><%= link_to 'VIEW', notification, class: "btn btn-info btn-sm w-100" %></td>
                <td><%= link_to 'EDIT', edit_notification_path(notification), class: "btn btn-primary btn-sm w-100" %></td>
                <td><%= link_to 'DESTROY', notification, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm w-100" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  <br>
<% end %>

<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col-2">
        <h5>Published Date</h5>
      </div>
      <div class="col">
        <h5>Notifications</h5>
      </div>
      <div class="col-1">
        <h5>Link</h5>
      </div>
    </div>
  </div>
  <div class="card-body">
    <% @notifications&.each do |notification| %>
        <div class="row">
          <div class="col-2">
            <p><%= notification.created_at.strftime("%d-%m-%Y") %></p>
          </div>
          <div class="col">
            <p><%= notification.title %></p>
          </div>
          <div class="col-1">
            <p><%= link_to 'Show', notification, class: "btn btn-outline-info btn-sm w-100" %></p>
          </div>
        </div>
        <hr class="m-2 p-0">
    <% end %>
  </div>
</div>
    

app/views/notifications/new.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    New Notification
  </h2>
  <div class="card-body">
    <%= render 'form', notification: @notification %>
    <%= link_to '< Back', notifications_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/notifications/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <strong>Title</strong>
      </div>
      <div class="col">
        <p><%= @notification.title %></p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Published at</strong>
      </div>
      <div class="col">
        <p><%= @notification.created_at %></p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>User</strong>
      </div>
      <div class="col">
        <p>
          <% if @notification.user.nil? %>
            admin@sea.svit.gmail.com
          <% else %>
            <%= "#{@notification.user&.name} (#{@notification.user&.role&.code}, #{@notification.user&.department&.code})" %>
          <% end %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Regulation</strong>
      </div>
      <div class="col">
        <p><%= @notification.regulation&.name || "All" %></p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Batch</strong>
      </div>
      <div class="col">
        <p><%= @notification.batch&.name || "All" %></p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Department</strong>
      </div>
      <div class="col">
        <p><%= @notification.department&.name || "All" %></p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Course</strong>
      </div>
      <div class="col">
        <p><%= @notification.course&.name || "All" %></p>
      </div>
    </div>

    <div class="row border rounded border-5 p-2 mb-2 border-opacity-75">
      <div class="col"><%= @notification.content %></div>
    </div>

    <div class="row text-center d-flex m-4">
      <div class="col">
        <%= link_to '< Back', notifications_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>