config/routes.rb
Rails.application.routes.draw do
  resources :departments  
  resources :members
  resources :results do
    collection {post :import }
  end

  resources :videos
  resources :tutorials
  resources :notifications
  resources :magazines
  
  resources :articles do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end

  resources :comments do
    resources :comments
  end

  resources :documents do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end
  
  get 'home/index'
  get 'home/search'
  devise_for :users, :skip => [:registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  #put 'approve_document', to: 'documents#approve_document', as: 'approve_document'
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
    belongs_to :user
    has_many :videos

    before_save :upcase_fields

    def upcase_fields
        self.title.upcase!
    end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tutorial, only: %i[ show edit update destroy ]
  before_action :authrize_access

  # GET /tutorials or /tutorials.json
  def index
    if current_user.is_hod?
      @your_tutorials = current_user.tutorials.all.order("id DESC")
    else
      @your_tutorials = []
    end
    @tutorials = Tutorial.all.order("id DESC")    
  end

  # GET /tutorials/1 or /tutorials/1.json
  def show
    @videos = @tutorial.videos.all
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials or /tutorials.json
  def create
    @tutorial = Tutorial.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to tutorials_path, notice: "Tutorial was successfully created." }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1 or /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to tutorials_path, notice: "Tutorial was successfully updated." }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1 or /tutorials/1.json
  def destroy
    @tutorial.destroy

    respond_to do |format|
      format.html { redirect_to tutorials_url, notice: "Tutorial was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    def authrize_access
      if current_user.is_student? || current_user.is_faculty?
        raise 'Unauthorized' unless (['index', 'show'].include?(params[:action]))
      else
        if ['edit', 'update', 'destroy'].include?(params[:action])
          raise 'Unauthorized' unless @tutorial.user == current_user
        elsif ['create', 'new'].include?(params[:action])
          raise 'Unauthorized' unless current_user.is_hod?
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def tutorial_params
      params.require(:tutorial).permit(:title, :user_id)
    end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_form.html.erb
<%= form_with(model: tutorial) do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
        <% tutorial.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-2">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", required: "required" %>
  </div>

  <div class="field d-none">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, :value => current_user.id %>
  </div>
  
  <div class="actions">
    <%= form.submit class: "btn btn-success mt-4" %>
  </div>
<% end %>

app/views/tutorials/edit.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    Editing Tutorial
  </h2>
  <div class="card-body">
    <%= render 'form', tutorial: @tutorial %>
    <%= link_to '< Back', tutorials_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/tutorials/index.html.erb
<% if current_user.is_hod? %>
  <%= link_to 'Create Tutorial', new_tutorial_path, class: "btn btn-primary mt-3 mb-3" %>

  <%= link_to 'Add Videos', videos_path, class: "btn btn-primary mt-3 mb-3" %>

  <button class="collapsible">Your Tutorials</button>
    <div class="content">
      <div class="table-responsive" >
        <table class="table table-bordered table-sm">
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col" colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @your_tutorials.each do |tutorial| %>
              <tr>
                <td><%= tutorial.title %></td>
                <td><%= link_to 'VIEW', tutorial, class: "btn btn-info btn-sm w-100" %></td>
                <td><%= link_to 'EDIT', edit_tutorial_path(tutorial), class: "btn btn-primary btn-sm w-100" %></td>
                <td><%= link_to 'DESTROY', tutorial, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm w-100" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
<% end %>

<div class="container">
  <div class="row d-flex">
    <% @tutorials.each do |tutorial| %>

      <div class="col m-4">
        <div class="card" style="width: 20rem;">
          <div class="card-body">  
            <p class="fw-bold m-0"><%= tutorial.title %></p>
            <small class="text-uppercase"><%= "#{tutorial.user.name} (#{tutorial.user.department.code})" %></small>
            <%= link_to 'VIEW', tutorial, class: "btn btn-info btn-sm w-100 mt-2" %>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/tutorials/new.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    New Tutorial
  </h2>
  <div class="card-body">
    <%= render 'form', tutorial: @tutorial %>
    <%= link_to '< Back', tutorials_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/tutorials/show.html.erb
<div class="row text-center bg-info m-1">
  <div class="col-lg-10">
    <p class="m-2 fw-bold"><%= @tutorial.title %></p>
  </div>
  <div class="col-lg-2">
    <%= link_to '< Back', tutorials_path, class: "m-1 btn btn-sm btn-secondary"
    %>
  </div>
</div>

<% @videos.each_with_index do |video, index| %>
<button class="collapsible"><%= "#{index+1} ) #{video.title}" %></button>
<div class="content">
  <div class="row">
   
    <div class="col-6">
      <div class="row mt-2">
        <div class="card">
          <div class="card-header fw-bold">Description</div>
          <div class="card-body"><%= video.content %></div>
        </div>
      </div>
    </div>

    <div class="col-6">
      <div class="row mt-2">
        <iframe width="560" height="315" src=<%= "https://www.youtube.com/embed/#{video.video_url.split("=")[1]}" %> title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>

  </div>
</div>
<% end %>