config/routes.rb
Rails.application.routes.draw do
  resources :departments  
  resources :members
  resources :results do
    collection {post :import }
  end

  resources :videos
  resources :tutorials
  resources :notifications
  resources :magazines
  
  resources :articles do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end

  resources :comments do
    resources :comments
  end

  resources :documents do
    resources :comments, only: [:create, :new]
    member do
      put :approve
      put :reject
    end
    collection do
      get :search
    end
  end
  
  get 'home/index'
  get 'home/search'
  devise_for :users, :skip => [:registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  #put 'approve_document', to: 'documents#approve_document', as: 'approve_document'
end

app/models/document.rb
class Document < ApplicationRecord
    has_rich_text :content
    belongs_to :user
    before_save :upcase_fields
    has_many :comments, as: :commentable
    
    APPROVED = 'Approved'
    IN_REVIEW = 'In Review'
    REJECTED = 'Rejected'

    validates :title, presence: true
    validates :keywords, presence: true
    validates :content, presence: true
    validates :user_id, presence: true

    belongs_to :reviewer1, class_name: 'User', foreign_key: 'reviewer1_id', optional: true
    belongs_to :reviewer2, class_name: 'User', foreign_key: 'reviewer2_id', optional: true
    belongs_to :reviewer3, class_name: 'User', foreign_key: 'reviewer3_id', optional: true

    def upcase_fields
        self.title.upcase!
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document, only: %i[ show edit update destroy approve reject]
  before_action :authrize_access


  # GET /documents or /documents.json
  def index
    @documents = current_user.documents.all.order("id DESC")
    if !current_user.is_student?
      @review_docs = Document.where("approval_status = :in_review AND (reviewer1_id IS NULL OR reviewer1_id != :user_id ) AND (reviewer2_id IS NULL OR reviewer2_id != :user_id) AND (reviewer3_id IS NULL OR reviewer3_id != :user_id)", {in_review: Document::IN_REVIEW, user_id: current_user.id}).order("id DESC")
      @approved_documents = Document.where("reviewer1_id = :user_id OR reviewer2_id = :user_id OR reviewer3_id = :user_id", {user_id: current_user.id}).order("id DESC")
    else
      @review_docs = []    
      @approved_documents = []
    end
  end

  # GET /documents/1 or /documents/1.json
  def show

    if @document.reference_url.present?
      url = URI("https://api.qrcode-monkey.com/qr/custom")
      https = Net::HTTP.new(url.host, url.port)
      https.use_ssl = true
      request = Net::HTTP::Post.new(url)
      request["Content-Type"] = "text/plain"
      request.body = {"data":"#{@document.reference_url}","config":{"body":"circle-zebra-vertical","eye":"frame13","eyeBall":"ball15","erf1":[],"erf2":[],"erf3":[],"brf1":[],"brf2":[],"brf3":[],"bodyColor":"#0277BD","bgColor":"#FFFFFF","eye1Color":"#075685","eye2Color":"#075685","eye3Color":"#075685","eyeBall1Color":"#0277BD","eyeBall2Color":"#0277BD","eyeBall3Color":"#0277BD","gradientColor1":"#075685","gradientColor2":"#0277BD","gradientType":"linear","gradientOnEyes":false,"logo":"https://raw.githubusercontent.com/shaik1729/sea/development/app/assets/images/sea_logo.jpeg","logoMode":"default"},"size":300,"download":false,"file":"png"}.to_json
      response = https.request(request)
      @qrcode = Base64.strict_encode64(response.read_body)
    else
      @qrcode = nil
    end

  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)
    
    if !current_user.is_student?
      @document.approval_status = Document::APPROVED
    else
      @document.approval_status = Document::IN_REVIEW
    end

    @document.reviewer1_id = nil
    @document.reviewer2_id = nil
    @document.reviewer3_id = nil

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def approve
    if @document.reviewer1_id == nil
      @document.reviewer1_id = current_user.id
    elsif @document.reviewer2_id == nil
      @document.reviewer2_id = current_user.id
    elsif @document.reviewer3_id == nil
      @document.reviewer3_id = current_user.id
      @document.approval_status = Document::APPROVED
      DocumentApprovalMailer.with(user: current_user, status: Document::APPROVED, document: @document).approval_status.deliver_later
    end

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: "Document Approved." }
        format.json { render :show, status: :approved, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end 
    end
  end

  def reject
    if @document.reviewer1_id == nil
      @document.reviewer1_id = current_user.id
    elsif @document.reviewer2_id == nil
      @document.reviewer2_id = current_user.id
    elsif @document.reviewer3_id == nil
      @document.reviewer3_id = current_user.id
    end
    @document.approval_status = Document::REJECTED

    respond_to do |format|
      if @document.save
        DocumentApprovalMailer.with(user: current_user, status: Document::REJECTED, document: @document, message: params[:reason]).approval_status.deliver_later
        format.html { redirect_to documents_path, notice: "Document Rejected." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end 
    end
  end

  def search
    if params[:id].empty?
      @documents = Document.where("approval_status = ? and title like ?", Document::APPROVED, "%#{params[:title]}%".upcase!).order("id DESC")
    else
      @documents = Document.where("approval_status = ? and id = ?", Document::APPROVED, params[:id][1..]).order("id DESC")
    end

    if @documents.empty?
      redirect_to documents_path, notice: "Document Not Found."
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    def authrize_access
      if current_user.is_student?
        raise Unauthorized unless (['index', 'new', 'create', 'show', 'search'].include?(params[:action]))
        if @document.present?
          raise Unauthorized if ((@document.user != current_user) && (@document.approval_status != Document::APPROVED))
        end 
      else
        if ['edit', 'update', 'destroy'].include?(params[:action])
          raise Unauthorized unless @document.user == current_user
        elsif ['approve', 'reject'].include?(params[:action])
          raise Unauthorized unless @document.user.is_student?
          if params[:action] == 'approve'
            raise Unauthorized if (@document.approval_status == Document::APPROVED)
          elsif params[:action] == 'reject'
            raise Unauthorized if (@document.approval_status == Document::REJECTED)
          end
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :keywords, :content, :approval_status, :reviewer1_id, :reviewer2_id, :reviewer3_id, :user_id, :reference_url)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
    def show_document_approve_button?
       (current_user.role.code != "STU") && (@document.approval_status == Document::IN_REVIEW) && !([@document.reviewer1, @document.reviewer2, @document.reviewer3].include? current_user)
    end

    def show_document_comments?
        @document.approval_status == Document::APPROVED
    end

    def show_document_approval_status?
        @document.user == current_user && current_user.is_student?
    end
end

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <div class="alert alert-danger" role="alert">
              <%= error.full_message %>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-2">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :keywords, class: "form-label" %>
    <%= form.text_field :keywords, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :content, class: "form-label" %>
    <%= form.rich_text_area :content, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :reference_url, class: "form-label" %>
    <%= form.text_field :reference_url, class: "form-control" %>
  </div>

  <div class="field d-none">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success mt-4" %>
  </div>
<% end %>

app/views/documents/_search_form.html.erb
<div class="card">
  <h2 class="card-header">
    Document Search
  </h2>
  <div class="card-body">
     <%= form_with url: search_documents_path, local: true, method: :get do  |f| %>
        <%= text_field_tag :id, params[:id], :placeholder => "Enter Document ID", class: "form-control me-2" %>
        <p>OR</p>
        <%= text_field_tag :title, params[:title], :placeholder => "Enter Document Title", class: "form-control me-2" %>
        <div class="actions mt-2">
            <%= f.submit "Search", class: "btn btn-success" %>
        </div>
    <% end %>
  </div>
</div>

app/views/documents/edit.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    Editing Document
  </h2>
  <div class="card-body">
    <%= render 'form', document: @document %>
    <%= link_to '< Back', documents_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/documents/index.html.erb
<%= render 'search_form' %>
<%= link_to 'New Document', new_document_path, class: "btn btn-primary mt-4 mb-4" %>

<button class="collapsible">Your Documents</button>
<div class="content">
  <div class="table-responsive">

      
      <table class="table table-bordered table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Keywords</th>
          <th scope="col" colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <td>D<%= document.id %></td>
            <td><%= document.title %></td>
            <td><%= document.keywords %></td>
            <td><%= link_to 'VIEW', document, class: "btn btn-info btn-sm w-100" %></td>
            <% if current_user.is_student? %>
              <td><%= document.approval_status %></td>
            <% else %>
              <td><%= link_to 'Edit', edit_document_path(document), class: "btn btn-primary btn-sm w-100" %></td>
              <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm w-100" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>
<% if !current_user.is_student? %>

<button class="collapsible">Awaiting Review Documents</button>
<div class="content">
  <div class="table-responsive">

    <table class="table table-bordered table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Uploaded By</th>
        <th scope="col">Approval status</th>
        <th scope="col">Reviewer1</th>
        <th scope="col">Reviewer2</th>
        <th scope="col">Reviewer3</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @review_docs.each do |document| %>
        <tr>
          <td>D<%= document.id %></td>
          <td><%= document.title %></td>
          <td><%= document.user.name %></td>
          <td><%= document.approval_status %></td>
          <td><%= document.reviewer1&.name %></td>
          <td><%= document.reviewer2&.name  %></td>
          <td><%= document.reviewer3&.name %></td>
          <td><%= link_to 'VIEW', document, class: "btn btn-info btn-sm w-100" %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
  </div>
</div>

<button class="collapsible">Reviewed Documents</button>
  <div class="content">
      <div class="table-responsive">

  <table class="table table-bordered table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Uploaded By</th>
          <th scope="col">Approval status</th>
          <th scope="col">Reviewer1</th>
          <th scope="col">Reviewer2</th>
          <th scope="col">Reviewer3</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @approved_documents.each do |document| %>
          <tr>
            <td>D<%= document.id %></td>
            <td><%= document.title %></td>
            <td><%= document.user.name %></td>
            <td><%= document.approval_status %></td>
            <td><%= document.reviewer1&.name %></td>
            <td><%= document.reviewer2&.name  %></td>
            <td><%= document.reviewer3&.name %></td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
  </div>
 
<% end %>

app/views/documents/new.html.erb
<div class="card mt-4">
  <h2 class="card-header">
    New Document
  </h2>
  <div class="card-body">
    <%= render 'form', document: @document %>
    <%= link_to '< Back', documents_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/documents/search.html.erb
<%= render 'search_form' %>

<div class="card mt-4">
  <h2 class="card-header">
    Search Results
  </h2>
  <div class="card-body">
    <div class="table-responsive">

    <table class="table table-bordered table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Keywords</th>
          <th scope="col">Author</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <td>D<%= document.id %></td>
            <td><%= document.title %></td>
            <td><%= document.keywords %></td>
            <td><%= "#{document.user.name} (#{document.user.role.name} #{document.user.department.code})" %></td>
            <td><%= link_to 'VIEW', document, class: "btn btn-info btn-sm w-100" %></td>
          </tr>
        <% end %>
      </tbody>

    </table>
    </div>
  </div>
</div>

app/views/documents/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <p>
          <strong>Title:</strong>
          <%= @document.title %>
        </p>

        <p>
          <strong>Keywords:</strong>
          <%= @document.keywords %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= "#{@document.user.name} (#{@document.user.role.name}, #{@document.user.department.name})" %>
        </p>
      </div>

      <% if @qrcode %>
          <div class="col">
            <p>
              <strong>Attachments/References:</strong>
              <br>
              <a href="<%= @document.reference_url %>" class="btn btn-primary" target="_blank">Click Here!</a>
            </p>
            <img src="data:image/jpeg;base64,<%= @qrcode %>">
          </div>
      <% end %>
    </div>

    <p>
      <%= @document.content %>
    </p>

    <% if show_document_approval_status? %>
      <p>
        <strong>Approval status:</strong>
        <%= @document.approval_status %>
      </p>

      <p>
        <strong>Reviewer1:</strong>
        <%= @document.reviewer1&.name %>
      </p>

      <p>
        <strong>Reviewer2:</strong>
        <%= @document.reviewer2&.name %>
      </p>

      <p>
        <strong>Reviewer3:</strong>
        <%= @document.reviewer3&.name %>
      </p>
    <% end %>


    <% if show_document_approve_button? %>
      <%= form_with url: approve_document_path, local: true, method: :put do  |f| %>
        <div class="actions mt-4 mb-4">
          <%= f.submit "Approve", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= form_with url: reject_document_path, local: true, method: :put do  |f| %>
        <%= text_field_tag :reason, params[:reason], :placeholder => "Enter Reason", class: "form-control me-2",:required => 'required' %>
        <div class="actions mt-4">
          <%= f.submit "Reject", class: "btn btn-danger" %>
        </div>
      <% end %>
    <% end %>

  </div>
</div>

<div class="card">
  <div class="card-body">
    <p>Commenting as</p>
    <div class="row mb-2">
      <div class="col comment_avatar_view">
        <iframe src="https://drive.google.com/file/d/<%= current_user.avatar_url %>/preview" class="avatar"></iframe>
        <p class="m-2"><%= current_user.name.upcase %></p>
      </div>
    </div>
    <%= form_for [@document, Comment.new], method: :post do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_area :content, placeholder: "Add a comment...", class: "form-control" %><br/>
        <%= f.submit "Comment", class: "btn btn-primary mb-4"  %>
    <% end %>

    <% if show_document_comments? %>
      <%= render partial: 'comments/comment', collection: @document.comments.order(id: :desc) %>
    <% end %>

  </div>
</div>